[Variables]

; LocationCode can be obtained at http://wxdata.weather.com/wxdata/search/search?where=YourCityName
LocationCode=USUT0191
; UnitOfMeasure can be "i" (Imperial / Fahrenheit) or "m" (Metric / Celsius)
;Change Units to match
UnitOfMeasure=i

; Number of days to return in the feed.(1-6) Don't change this if you are not modifying this skin
DaysFeed=1


; Locale (language) to use in the feed.
; https://msdn.microsoft.com/en-us/goglobal/bb896001.aspx
; Note that Weather.com uses "_" underline instead of "-" dash in the codes.
Locale=en_US